### PR TITLE
ext: add extension options

### PR DESCRIPTION
**Pull request by sornas**
adding more and more options to the popup view is not sustainable. instead, use the built-in extension setting support.

references:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages
- https://github.com/mdn/webextensions-examples/tree/main/favourite-colour

image
image

### CODE REVIEW

**Comment by l0f3n** [comment]
Nice, some minor ui stuff, look into them if you want.

1. extra spacing between leave and settings, just like between name and join
2. can you use our special font for the settings page? doesnt look like its in use now
3. instead of "open settings", maybe just settings. also maybe of those "this button will open another page"-icon, you probably know what i mean. cannot take screenshot right now. an arrow going out from inside a square.

**Review by l0f3n — APPROVED** [review]

**Comment by sornas** [comment]
i think i prefer "open settings" because it's a verb like the other buttons. i'll fix the other things though, thanks!

**Comment by sornas** [comment]
here's the updated popup. i went with google material icons (well, icon) because i don't know any better.

image

**Comment by sornas** [comment]
i can't get rid of the bar around it but it looks much better!

image

**Pull request merged**
